server:
  port: 6060

spring:
  application:
    name: trading-platform
  sql:
    init:
      data-locations: classpath:sql/data.sql

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %thread | %-5level | %logger{36} | %msg%n"