spring:
  application:
    name: reactive-apis-crud
  sql:
    init:
      data-locations: classpath:sql/data.sql

logging:
  level:
    root: INFO
    #org.springframework.r2dbc: DEBUG    # For logging R2DBC queries.
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %msg%n"
